/* Eje 4 – Intervención del Ministerio Público en materia penal: Ley 906 de 2004, Ley 599 de 2000, Ley 1826 de 2017, SRPA (Ley 1098 de 2006), extinción de dominio, JEP */
window.BANCO = window.BANCO || [];
window.BANCO.push(
{ id:'E4-01', eje:'E4', tipo:'C', tema:'Solicitud probatoria del Ministerio Público en el juicio', nivel:'aplicación',
  caso:'En la audiencia preparatoria, agotadas las solicitudes probatorias de la Fiscalía y la defensa, el Procurador Judicial I advierte que existe un dictamen que ninguna de las partes pidió y que podría tener influencia esencial en el resultado del juicio.',
  enunciado:'Conforme a la Ley 906 de 2004, el Procurador',
  opciones:[
   'no puede solicitar pruebas en ningún caso, porque el sistema acusatorio reserva la actividad probatoria a las partes.',
   'puede solicitar excepcionalmente la práctica de esa prueba, precisamente porque las partes agotaron sus solicitudes y la prueba podría tener esencial influencia en los resultados del juicio.',
   'puede pedir al juez que decrete la prueba de oficio.',
   'debe presentar la prueba directamente en el juicio oral sin descubrirla.'],
  correcta:1,
  explicacion:'El inciso final del artículo 357 de la Ley 906 de 2004 dispone que, excepcionalmente, agotadas las solicitudes probatorias de las partes, si el Ministerio Público tuviere conocimiento de la existencia de una prueba no pedida por estas que pudiere tener esencial influencia en los resultados del juicio, solicitará su práctica. El juez de conocimiento no puede decretar pruebas de oficio (art. 361). Toda prueba debe ser descubierta y decretada en la audiencia preparatoria.',
  fuente:'Ley 906 de 2004, arts. 357 (inciso final) y 361; Corte Constitucional, C-209 de 2007 y C-144 de 2010.' },

{ id:'E4-02', eje:'E4', tipo:'C', tema:'Principio de oportunidad', nivel:'aplicación',
  caso:'La Fiscalía informa al Procurador Judicial I que aplicará el principio de oportunidad en la modalidad de suspensión del procedimiento a prueba frente a un imputado por hurto, y pregunta si requiere alguna actuación adicional.',
  enunciado:'El Procurador debe recordar que',
  opciones:[
   'la aplicación del principio de oportunidad es discrecional de la Fiscalía y no requiere control judicial.',
   'el juez de control de garantías debe efectuar el control de legalidad, obligatorio y automático, dentro de los cinco días siguientes, en audiencia en la que la víctima y el Ministerio Público pueden controvertir la prueba aducida por la Fiscalía.',
   'la decisión debe ser aprobada por el juez de conocimiento en la audiencia de acusación.',
   'el Ministerio Público debe autorizar previamente la aplicación del principio de oportunidad.'],
  correcta:1,
  explicacion:'El artículo 327 de la Ley 906 de 2004 establece que el juez de control de garantías realizará el control de legalidad de las solicitudes de aplicación del principio de oportunidad, obligatorio y automático, dentro de los cinco días siguientes a la determinación de la Fiscalía, en audiencia especial en la que la víctima y el Ministerio Público podrán controvertir la prueba. Las causales están en el artículo 324 y algunas requieren autorización del Fiscal General o su delegado; el principio no procede frente a graves infracciones al DIH, delitos de lesa humanidad, genocidio ni delitos contra la libertad sexual de menores, entre otras exclusiones.',
  fuente:'Ley 906 de 2004, arts. 321 a 330, en especial 324 y 327; Ley 1312 de 2009.' },

{ id:'E4-03', eje:'E4', tipo:'C', tema:'Preacuerdos y reintegro del incremento patrimonial', nivel:'aplicación',
  caso:'En un proceso por peculado por apropiación, la Fiscalía y el acusado presentan un preacuerdo que degrada la conducta a título de cómplice. El acusado no ha reintegrado suma alguna. El Procurador Judicial I es oído.',
  enunciado:'El Procurador debe oponerse porque',
  opciones:[
   'los preacuerdos están prohibidos en delitos contra la administración pública.',
   'en los delitos en que el sujeto activo obtuvo incremento patrimonial fruto del delito, no puede celebrarse preacuerdo hasta tanto se reintegre por lo menos el cincuenta por ciento del valor equivalente al incremento y se asegure el recaudo del remanente.',
   'el Ministerio Público tiene derecho de veto sobre los preacuerdos.',
   'la degradación a cómplice solo procede en la audiencia de imputación.'],
  correcta:1,
  explicacion:'El artículo 349 de la Ley 906 de 2004 dispone que en los delitos en los cuales el sujeto activo haya obtenido incremento patrimonial fruto del mismo no se podrá celebrar acuerdo hasta que reintegre, por lo menos, el cincuenta por ciento del valor equivalente al incremento percibido y asegure el recaudo del remanente. El Ministerio Público y la víctima son oídos (art. 351) pero no tienen veto; el juez solo puede rechazar el preacuerdo cuando desconozca o quebrante garantías fundamentales.',
  fuente:'Ley 906 de 2004, arts. 348 a 351, en especial 349 y 351 inc. 4; CSJ, Sala de Casación Penal, jurisprudencia sobre control judicial de preacuerdos.' },

{ id:'E4-04', eje:'E4', tipo:'C', tema:'Rebajas por allanamiento y flagrancia', nivel:'aplicación',
  caso:'Un capturado en flagrancia por hurto calificado se allana a los cargos en la audiencia de formulación de imputación. La defensa pide la rebaja de hasta la mitad de la pena.',
  enunciado:'El Procurador Judicial I debe precisar que',
  opciones:[
   'procede la rebaja de hasta la mitad, porque el allanamiento se produjo en la imputación.',
   'quien es capturado en flagrancia solo tiene derecho a la cuarta parte del beneficio previsto para el allanamiento, es decir, hasta un 12,5 % de rebaja cuando se allana en la imputación.',
   'la flagrancia excluye por completo cualquier rebaja de pena.',
   'la rebaja aplicable es de una tercera parte, propia de la audiencia de acusación.'],
  correcta:1,
  explicacion:'El artículo 351 de la Ley 906 de 2004 prevé rebaja de hasta la mitad de la pena por aceptación de cargos en la imputación (hasta una tercera parte en la acusación, art. 352, y una sexta parte al inicio del juicio oral, art. 367). Sin embargo, el parágrafo del artículo 301, adicionado por la Ley 1453 de 2011, dispone que la persona capturada en flagrancia que se allane solo tendrá la cuarta parte del beneficio de que trata el artículo 351, lo que la Sala de Casación Penal ha interpretado como el 12,5 % de rebaja en la imputación.',
  fuente:'Ley 906 de 2004, arts. 301 (parágrafo, Ley 1453 de 2011), 351, 352 y 367; CSJ SP, sentencia rad. 38285 de 2012.' },

{ id:'E4-05', eje:'E4', tipo:'C', tema:'Legitimación para solicitar medida de aseguramiento', nivel:'aplicación',
  caso:'En audiencia de imputación por lesiones personales dolosas, el fiscal decide no solicitar medida de aseguramiento. La víctima, sin abogado, pide al Procurador Judicial I que la solicite él.',
  enunciado:'La respuesta jurídicamente correcta es que',
  opciones:[
   'el Ministerio Público puede solicitar la medida de aseguramiento porque actúa como garante de la víctima.',
   'la solicitud de medida de aseguramiento corresponde al fiscal y, conforme a la jurisprudencia constitucional, también puede formularla directamente la víctima o su apoderado; el Ministerio Público no está legitimado para pedirla, pero puede pronunciarse sobre su procedencia.',
   'la medida solo puede imponerla el juez de oficio.',
   'la víctima carece de cualquier facultad para pedir medidas de aseguramiento.'],
  correcta:1,
  explicacion:'El artículo 306 de la Ley 906 de 2004 atribuye al fiscal la solicitud de medida de aseguramiento; la Corte Constitucional (C-209 de 2007) reconoció a la víctima la facultad de solicitarla directamente al juez de control de garantías, y la Ley 1826 de 2017 lo recogió expresamente. El Ministerio Público, como interviniente garante, no está legitimado para pedirla, aunque puede conceptuar. La medida solo procede si concurren la inferencia razonable de autoría y alguno de los fines del artículo 308 (obstrucción, peligro para la comunidad o la víctima, no comparecencia).',
  fuente:'Ley 906 de 2004, arts. 306 a 308; Corte Constitucional, C-209 de 2007; Ley 1826 de 2017.' },

{ id:'E4-06', eje:'E4', tipo:'C', tema:'Libertad por vencimiento de términos', nivel:'aplicación',
  caso:'Un imputado con detención preventiva por un delito de competencia de juez penal del circuito lleva 70 días desde la formulación de imputación sin que la Fiscalía haya presentado escrito de acusación. Es el único imputado y no hay concurso de delitos.',
  enunciado:'El Procurador Judicial I, como garante de la libertad, debe advertir que',
  opciones:[
   'no procede la libertad, pues el término para acusar es de 120 días.',
   'procede la libertad por vencimiento de términos, porque transcurrieron más de 60 días desde la imputación sin presentación del escrito de acusación, término que solo se amplía a 90 días cuando hay tres o más imputados o delitos de competencia de los jueces penales del circuito especializados.',
   'la libertad solo procede cuando el imputado lleve más de un año privado de la libertad.',
   'el término se cuenta desde la captura y ya venció el de 36 horas, por lo que procede el habeas corpus.'],
  correcta:1,
  explicacion:'El artículo 317 de la Ley 906 de 2004, modificado por las Leyes 1453 de 2011, 1760 de 2015 y 1786 de 2016, prevé la libertad cuando transcurridos 60 días desde la formulación de imputación no se ha presentado escrito de acusación (o solicitado preclusión), término que se amplía a 90 días cuando se trate de tres o más imputados o de delitos de competencia de los jueces penales del circuito especializado. También hay causales por 120 días entre acusación e inicio del juicio, y 150 días entre inicio del juicio y anuncio del sentido del fallo. Además, la detención preventiva no puede exceder de un año, prorrogable en casos especiales (art. 307 parágrafo).',
  fuente:'Ley 906 de 2004, arts. 307 (par.) y 317 (Leyes 1453 de 2011, 1760 de 2015 y 1786 de 2016).' },

{ id:'E4-07', eje:'E4', tipo:'C', tema:'Incidente de reparación integral', nivel:'aplicación',
  caso:'Tras la firmeza de una sentencia condenatoria por lesiones personales, la víctima, de escasos recursos y sin abogado, pide al Procurador Judicial I que abra el incidente de reparación integral en su nombre.',
  enunciado:'Conforme al artículo 102 de la Ley 906 de 2004, el Procurador',
  opciones:[
   'puede solicitar la apertura del incidente a instancia de la víctima, dentro de los treinta días siguientes a la firmeza de la sentencia condenatoria.',
   'no puede intervenir en el incidente, porque es un trámite exclusivamente civil.',
   'debe abrir el incidente de oficio, pues es su deber procurar la reparación.',
   'solo puede intervenir si la víctima otorga poder a la Defensoría del Pueblo.'],
  correcta:0,
  explicacion:'El artículo 102 de la Ley 906 de 2004 (modificado por la Ley 1395 de 2010) dispone que, en firme la sentencia condenatoria y previa solicitud expresa de la víctima, o del fiscal o del Ministerio Público a instancia de ella, el juez abrirá inmediatamente el incidente de reparación integral. La solicitud debe presentarse dentro de los treinta días siguientes a la firmeza de la sentencia (art. 106). El Ministerio Público no actúa de oficio en este trámite sino a instancia de la víctima.',
  fuente:'Ley 906 de 2004, arts. 102 a 108 (Ley 1395 de 2010, art. 86).' },

{ id:'E4-08', eje:'E4', tipo:'C', tema:'Prueba de referencia', nivel:'análisis',
  caso:'La única prueba de cargo en un juicio por acceso carnal violento es la entrevista rendida por la víctima ante la Policía Judicial, incorporada porque la víctima falleció antes del juicio. La defensa pide absolución.',
  enunciado:'Frente a la Ley 906 de 2004, el análisis correcto es que',
  opciones:[
   'la entrevista es inadmisible en todo caso, porque las declaraciones anteriores al juicio nunca pueden ingresar.',
   'la entrevista es admisible como prueba de referencia por la muerte del declarante, pero la sentencia condenatoria no puede fundamentarse exclusivamente en prueba de referencia.',
   'la entrevista tiene pleno valor y basta para condenar, porque la víctima falleció.',
   'la entrevista debe valorarse como prueba directa por tratarse de un delito sexual.'],
  correcta:1,
  explicacion:'La prueba de referencia (art. 437) es excepcionalmente admisible cuando el declarante ha fallecido, perdió la memoria, fue secuestrado, padece enfermedad grave que le impide declarar, entre otros supuestos (art. 438; Ley 1652 de 2013 para menores víctimas de delitos sexuales). Sin embargo, el inciso segundo del artículo 381 establece que la sentencia condenatoria no podrá fundamentarse exclusivamente en pruebas de referencia. El estándar para condenar es el conocimiento más allá de toda duda razonable.',
  fuente:'Ley 906 de 2004, arts. 381 inc. 2, 437 y 438; Ley 1652 de 2013.' },

{ id:'E4-09', eje:'E4', tipo:'C', tema:'Cadena de custodia: exclusión vs. valoración', nivel:'análisis',
  caso:'La defensa solicita excluir un arma incautada porque en el formato de cadena de custodia faltan dos firmas de los funcionarios que la trasladaron.',
  enunciado:'El Procurador Judicial I debe conceptuar que',
  opciones:[
   'la irregularidad en la cadena de custodia genera la exclusión automática del elemento por ilicitud.',
   'las irregularidades en la cadena de custodia no generan exclusión, porque no afectan derechos fundamentales; inciden en la autenticidad y el valor probatorio del elemento, que puede demostrarse por otros medios.',
   'el elemento debe excluirse por violación del artículo 29 de la Constitución.',
   'el arma debe destruirse y el juicio anularse.'],
  correcta:1,
  explicacion:'La cláusula de exclusión (arts. 23 y 455 de la Ley 906 de 2004) opera frente a pruebas obtenidas con violación de garantías fundamentales (prueba ilícita) y sus derivadas, con las excepciones del vínculo atenuado, la fuente independiente y el descubrimiento inevitable. La Sala de Casación Penal ha sostenido de manera reiterada que los defectos en la cadena de custodia (arts. 254 a 266) no conducen a la exclusión sino que afectan la autenticidad y, por ende, el mérito probatorio del elemento, autenticidad que puede acreditarse por otros medios (art. 277).',
  fuente:'Ley 906 de 2004, arts. 23, 254 a 266, 277 y 455; CSJ SP, rad. 25920 de 2007 y jurisprudencia posterior.' },

{ id:'E4-10', eje:'E4', tipo:'C', tema:'Control posterior de registro y allanamiento', nivel:'aplicación',
  caso:'Una fiscal ordenó un allanamiento a una vivienda y la diligencia se practicó un viernes a las 10 p. m. La defensa alega que la orden debía ser previa del juez de control de garantías.',
  enunciado:'La posición jurídicamente correcta es que',
  opciones:[
   'la Fiscalía puede ordenar registros y allanamientos, pero debe comparecer ante el juez de control de garantías dentro de las 24 horas siguientes al cumplimiento de la orden para la audiencia de revisión de legalidad.',
   'el allanamiento es ilegal porque requiere siempre orden judicial previa.',
   'el allanamiento es legal y no requiere control judicial alguno.',
   'el control de legalidad debe realizarse dentro de las 36 horas, contadas desde la captura.'],
  correcta:0,
  explicacion:'El artículo 250-2 de la Constitución (AL 03 de 2002) faculta a la Fiscalía para adelantar registros, allanamientos, incautaciones e interceptaciones de comunicaciones con control posterior del juez de control de garantías. El artículo 237 de la Ley 906 de 2004 (modificado por la Ley 1142 de 2007) fija en 24 horas el término para que el fiscal comparezca ante el juez de garantías para la audiencia de revisión de legalidad. El Ministerio Público puede asistir a esa audiencia.',
  fuente:'CP art. 250 num. 2; Ley 906 de 2004, arts. 219 a 232 y 237 (Ley 1142 de 2007).' },

{ id:'E4-11', eje:'E4', tipo:'C', tema:'Doble conformidad', nivel:'comprensión',
  caso:'Un acusado absuelto en primera instancia es condenado por primera vez por el Tribunal Superior al resolver la apelación de la Fiscalía. Su defensor pregunta al Procurador Judicial I qué mecanismo tiene para controvertir la condena.',
  enunciado:'La orientación correcta es que',
  opciones:[
   'solo procede el recurso extraordinario de casación, con sus causales taxativas.',
   'procede la impugnación especial ante la Sala de Casación Penal de la Corte Suprema de Justicia, en garantía del derecho a impugnar la primera sentencia condenatoria (doble conformidad), reconocido por el Acto Legislativo 01 de 2018.',
   'la condena en segunda instancia es inimpugnable.',
   'procede la acción de tutela como único mecanismo.'],
  correcta:1,
  explicacion:'El artículo 29 de la Constitución consagra el derecho a impugnar la sentencia condenatoria, desarrollado por la Corte Constitucional (C-792 de 2014, SU-215 de 2016) y por el Acto Legislativo 01 de 2018, que modificó los artículos 186, 234 y 235 superiores para garantizar la doble conformidad. La Sala de Casación Penal habilitó la impugnación especial contra las primeras condenas impuestas en segunda instancia por los tribunales, mecanismo distinto de la casación por su amplitud.',
  fuente:'CP art. 29; AL 01 de 2018; Corte Constitucional, C-792 de 2014 y SU-217 de 2019; CSJ SP, AP1263-2019 y jurisprudencia sobre impugnación especial.' },

{ id:'E4-12', eje:'E4', tipo:'C', tema:'Procedimiento penal abreviado (Ley 1826 de 2017)', nivel:'comprensión',
  caso:'En un proceso por inasistencia alimentaria tramitado bajo el procedimiento abreviado, la defensa reclama que nunca se realizó audiencia de formulación de imputación.',
  enunciado:'El Procurador Judicial I debe explicar que en el procedimiento abreviado',
  opciones:[
   'la imputación se formula por escrito ante el juez de control de garantías.',
   'la formulación de imputación fue sustituida por el traslado del escrito de acusación, con el cual se activan los derechos del indiciado, y el proceso se concentra en la audiencia concentrada y el juicio oral.',
   'la imputación es reemplazada por la querella.',
   'no existe etapa alguna anterior al juicio.'],
  correcta:1,
  explicacion:'La Ley 1826 de 2017 creó el procedimiento penal abreviado para los delitos querellables y otros expresamente señalados: el fiscal, en lugar de formular imputación, corre traslado del escrito de acusación al indiciado, acto que interrumpe la prescripción y activa las garantías; luego se surten la audiencia concentrada (ante juez de conocimiento) y el juicio oral. La ley creó además la figura del acusador privado, que exige conversión de la acción penal autorizada por el fiscal. El Ministerio Público conserva sus facultades de intervención.',
  fuente:'Ley 1826 de 2017 (arts. 534 a 564 de la Ley 906 de 2004).' },

{ id:'E4-13', eje:'E4', tipo:'C', tema:'Sistema de Responsabilidad Penal para Adolescentes', nivel:'aplicación',
  caso:'Un adolescente de 15 años es declarado responsable de hurto calificado (pena mínima inferior a seis años). El fiscal pide privación de la libertad en centro de atención especializado.',
  enunciado:'El Procurador Judicial I de familia debe oponerse porque',
  opciones:[
   'los menores de 16 años no son responsables penalmente.',
   'la privación de la libertad en centro de atención especializado solo procede para adolescentes mayores de 16 y menores de 18 años hallados responsables de delitos cuya pena mínima sea o exceda de seis años, y para los de 14 a 18 años en homicidio doloso, secuestro, extorsión y delitos agravados contra la libertad, integridad y formación sexuales.',
   'la sanción para adolescentes siempre es la amonestación.',
   'la privación de la libertad de adolescentes fue prohibida por la Ley 1098 de 2006.'],
  correcta:1,
  explicacion:'El artículo 187 de la Ley 1098 de 2006 (modificado por la Ley 1453 de 2011) reserva la privación de la libertad en centro de atención especializado a los adolescentes mayores de 16 y menores de 18 años responsables de delitos cuya pena mínima establecida en el Código Penal sea o exceda de seis años de prisión (sanción de uno a cinco años), y a los de 14 a 18 años en los delitos de homicidio doloso, secuestro, extorsión en todas sus formas y delitos agravados contra la libertad, integridad y formación sexuales (dos a ocho años). Los menores de 14 años no son penalmente responsables (art. 142). Las sanciones del SRPA tienen finalidad protectora, educativa y restaurativa (art. 178).',
  fuente:'Ley 1098 de 2006, arts. 139 a 191, en especial 142, 177, 178 y 187 (Ley 1453 de 2011).' },

{ id:'E4-14', eje:'E4', tipo:'C', tema:'Prescripción de la acción penal e interrupción', nivel:'aplicación',
  caso:'Un servidor público es imputado por prevaricato por acción (pena máxima de 12 años) cometido en ejercicio de sus funciones. La defensa sostiene que el término de prescripción es de 12 años sin más.',
  enunciado:'El análisis correcto es que',
  opciones:[
   'el término inicial es igual al máximo de la pena (12 años) y no admite modificación.',
   'el término inicial es igual al máximo de la pena aumentado en la mitad por tratarse de servidor público en ejercicio de sus funciones; con la formulación de imputación se interrumpe y comienza a correr de nuevo por la mitad del término, sin ser inferior a cinco años ni superior a diez.',
   'la prescripción no opera en delitos contra la administración pública.',
   'la imputación no afecta el término de prescripción.'],
  correcta:1,
  explicacion:'El artículo 83 del Código Penal fija la prescripción en un tiempo igual al máximo de la pena, no inferior a cinco ni superior a veinte años, y ordena aumentarlo en la mitad cuando el delito es cometido por servidor público en ejercicio de sus funciones o con ocasión de ellas. El artículo 86 (modificado por la Ley 890 de 2004) dispone que la prescripción se interrumpe con la formulación de imputación y comienza a correr de nuevo por la mitad del término del artículo 83, sin que pueda ser inferior a cinco años ni superior a diez.',
  fuente:'Ley 599 de 2000, arts. 83 y 86 (Ley 890 de 2004; Ley 1474 de 2011).' },

{ id:'E4-15', eje:'E4', tipo:'C', tema:'Nulidades en el proceso penal', nivel:'aplicación',
  caso:'En la audiencia de formulación de acusación, el Procurador Judicial I advierte que el imputado fue asistido en la imputación por un estudiante de consultorio jurídico sin habilitación legal para ese tipo de proceso.',
  enunciado:'La actuación procedente del Procurador es',
  opciones:[
   'guardar silencio, pues las nulidades solo pueden ser alegadas por la defensa.',
   'solicitar la declaratoria de nulidad por violación del derecho de defensa, en la oportunidad prevista para ello en la audiencia de acusación, acreditando la trascendencia de la irregularidad.',
   'pedir la absolución inmediata del acusado.',
   'solicitar la exclusión de toda la prueba de la Fiscalía.'],
  correcta:1,
  explicacion:'El artículo 339 de la Ley 906 de 2004 prevé que en la audiencia de formulación de acusación se expresen las causales de incompetencia, impedimentos, recusaciones y nulidades. Las causales de nulidad son taxativas (art. 458): prueba ilícita, incompetencia del juez y violación del derecho de defensa o del debido proceso en aspectos sustanciales (arts. 455 a 457). El Ministerio Público, como garante, está facultado para solicitar nulidades y debe observar los principios de trascendencia, convalidación y residualidad.',
  fuente:'Ley 906 de 2004, arts. 111, 339 y 455 a 458.' },

{ id:'E4-16', eje:'E4', tipo:'C', tema:'Extinción de dominio', nivel:'comprensión',
  caso:'El titular de un inmueble afectado con medida de extinción de dominio alega que la acción no procede porque el proceso penal en su contra terminó por prescripción.',
  enunciado:'El Procurador Judicial que interviene debe señalar que la acción de extinción de dominio',
  opciones:[
   'depende de una condena penal previa, por lo que la prescripción penal la extingue.',
   'es autónoma e independiente de cualquier declaratoria de responsabilidad penal, de naturaleza real, jurisdiccional y de carácter patrimonial, e imprescriptible.',
   'solo procede respecto de bienes de origen lícito destinados a actividades ilícitas.',
   'debe ejercerse dentro de los cinco años siguientes a la comisión del delito.'],
  correcta:1,
  explicacion:'El Código de Extinción de Dominio (Ley 1708 de 2014) define la acción como constitucional, pública, jurisdiccional, directa, de carácter real y de contenido patrimonial, autónoma e independiente de cualquier otro juicio o proceso, en especial de la declaratoria de responsabilidad penal, e imprescriptible. Procede tanto sobre bienes de origen ilícito como sobre bienes de origen lícito destinados a actividades ilícitas, entre otras causales (art. 16). El Ministerio Público interviene en defensa del orden jurídico, del patrimonio público y de los derechos fundamentales.',
  fuente:'CP art. 34; Ley 1708 de 2014, arts. 15 a 21 (naturaleza e imprescriptibilidad) y 16 (causales).' },

{ id:'E4-17', eje:'E4', tipo:'C', tema:'Jurisdicción Especial para la Paz y Ministerio Público', nivel:'comprensión',
  caso:'Un excombatiente compareciente ante la JEP reconoce verdad plena y responsabilidad en la etapa inicial. Pregunta al Procurador Judicial I qué tipo de sanción podría recibir.',
  enunciado:'Conforme a la Ley 1957 de 2019, la respuesta correcta es que',
  opciones:[
   'recibirá necesariamente pena de prisión de 15 a 20 años.',
   'podrá recibir una sanción propia, de cinco a ocho años de restricción efectiva de libertades y derechos con componente restaurativo; las sanciones alternativas (prisión de cinco a ocho años) aplican a quien reconoce tardíamente y las ordinarias (hasta veinte años) a quien no reconoce y es vencido en juicio.',
   'la JEP no impone sanciones, solo otorga amnistías.',
   'recibirá amnistía automática por cualquier delito.'],
  correcta:1,
  explicacion:'La Ley Estatutaria 1957 de 2019 (arts. 125 a 130) prevé sanciones propias para quienes reconozcan verdad y responsabilidad ante la Sala de Reconocimiento (cinco a ocho años de restricción efectiva de libertades y derechos, con contenido restaurativo y reparador), sanciones alternativas para quienes reconozcan antes de la sentencia en el juicio (prisión de cinco a ocho años) y sanciones ordinarias para quienes no reconozcan y sean condenados (prisión de quince a veinte años). Las amnistías no cubren crímenes de lesa humanidad, genocidio, graves crímenes de guerra ni otros delitos excluidos. La Procuraduría interviene ante la JEP mediante procuradores delegados para la garantía de los derechos de las víctimas.',
  fuente:'AL 01 de 2017; Ley 1957 de 2019, arts. 125 a 130; Ley 1820 de 2016 (amnistía).' },

{ id:'E4-18', eje:'E4', tipo:'C', tema:'Estándar de conocimiento para condenar', nivel:'comprensión',
  caso:'Al final del juicio, el fiscal sostiene que existen “altas probabilidades” de responsabilidad y pide condena. La defensa alega que ese estándar es insuficiente.',
  enunciado:'El Procurador Judicial I debe recordar que, conforme al artículo 381 de la Ley 906 de 2004, para condenar se requiere',
  opciones:[
   'la probabilidad prevalente de la responsabilidad, como en materia civil.',
   'el conocimiento más allá de toda duda razonable acerca del delito y de la responsabilidad penal del acusado, fundado en las pruebas debatidas en el juicio.',
   'la inferencia razonable de autoría, propia de la imputación.',
   'la certeza absoluta, matemáticamente demostrada.'],
  correcta:1,
  explicacion:'El artículo 381 de la Ley 906 de 2004 exige, para condenar, el conocimiento más allá de toda duda acerca del delito y de la responsabilidad penal del acusado, fundado en las pruebas debatidas en el juicio; la duda razonable se resuelve en favor del procesado (art. 7). Los estándares menores corresponden a otras etapas: inferencia razonable de autoría para imputar y para imponer medida de aseguramiento; probabilidad de verdad para acusar (art. 336).',
  fuente:'Ley 906 de 2004, arts. 7, 287, 308, 336 y 381.' }
);
